---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Watzdprice Service"
  license:
    name: "MIT"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /updateproduct:
    put:
      description: "Updates `product` objects"
      operationId: "updateproductPUT"
      parameters:
      - in: "body"
        name: "product"
        description: "The `product` to update"
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        200:
          description: "Product is succesfully updated"
          schema:
            title: "Operation"
            type: object
            properties:
              operation:
                type: string
                description: "added or updated"
            required: ["operation"]
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
  /addshoploadstats:
    post:
      description: "Add a new shop load status line"
      operationId: "addshoploadstatsPOST"
      parameters:
      - in: "body"
        name: "shoploadstats"
        description: "The `shoploadstats` to add"
        required: true
        schema:
          $ref: "#/definitions/ShopLoadStats"
      responses:
        204:
          description: "ShopLoadStats is succesfully added"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Default"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  Product:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The product name"
        maxLength: 256
      description:
        type: "string"
        description: "The product description"
      shop:
        type: "string"
        description: "The shop name"
        maxLength: 256
      brand:
        type: "string"
        description: "The brand name"
        maxLength: 256
      eancode:
        type: "string"
        description: "The product eancode"
        maxLength: 256
      category:
        type: "string"
        description: "The product category"
        maxLength: 256
      url:
        type: "string"
        description: "The product url"
      image:
        type: "string"
        description: "The product image"
      price:
        type: "number"
        format: "float"
        description: "The product price"
      datetime:
        type: "string"
        format: "date-time"
        description: "The price datetime"
    required: ["name", "shop", "url", "price", "datetime"]
  ShopLoadStats:
    type: "object"
    properties:
      shop:
        type: "string"
        description: "The shop name"
        maxLength: 256
      start:
        type: "string"
        format: "date-time"
        description: "The start of the load"
      end:
        type: "string"
        format: "date-time"
        description: "The end of the load"
      added:
        type: "integer"
        format: "int64"
        description: "The number of new products added"
      updated:
        type: "integer"
        format: "int64"
        description: "The number of existing products updated"
    required: ["shop", "start", "end", "added", "updated"]
